apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: YSQL
    type: postgres
    access: proxy
    url: yb:5433
    user: yugabyte
    jsonData:
      database: "testdb"
      sslmode: "disable"
